import java.util.List;

public class Constants {


    public static List<String> TWEETS = List.of(
            "@JetBlue I was not allowed to drop my bag off for my flight that I was running 10min Late Flight for. Turns out it left over an hour Late Flight.",
            "@JetBlue was just at T5 a little over a month ago. @JetBlue you guys are great thanks for everything!",
            "@SouthwestAir what does relay concerns really mean &amp; how/why do u keep letting people on flights with bags larger than u state are allowabl?",
            "@AmericanAir please rebook me from Seattle to Columbus Tue 2/24, locator: KARAAX, name: Mitchell M Neuer",
            "@SouthwestAir I have been in contact and know there are changes but it's a destination you should really evaluate! Thanks",
            "@united You load our plane at ORD knowing pilots are 2 hrs Late Flight, then discover plane needs to be fueled? #WTF #united #incompetent",
            "@AmericanAir Also, I have to wait more than 2 hours before I can speak to someone on the phone?  I can't wait 2 hours.  :(",
            "@united Thank you for responding so quickly with a helpful tool! @dustyob",
            "@VirginAmerica This is what you missed @NewsVP. Next trip to the 407.",
            "@JetBlue @BrandsSayingBae well here we go",
            "@AmericanAir gate agents disappeared and customer service agents were miserable and unhelpful. #letdown #neveragain",
            "@USAirways Plus a US Airways - you need to do something about this! I left Philly to thaw out!!!! http://t.co/pKy7ZhnNRH",
            "@AmericanAir how does one book a ticket online and put it on hold?  Does that require that I pay for the ticket?",
            ".@SouthwestAir she needs a wheelchair at the gate for sure. What options does she have?",
            "@united also why can't I pre-select seats on SFO-&gt;YYZ flight? I'm a Canadian Flight Booking Problems on http://t.co/aZltJhf7lv.",
            "@USAirways delayed depart bc ur flight attendant wasn't there. Then after landing took 3 hrs to get a gate. Now it's another he and NO bags",
            "@USAirways is useless airways. Day 2 trying to get home on standby as a result of their Cancelled Flightlation. #USAirways",
            "@SouthwestAir I had to travel to Savannah, GA, once again, on an airline I don't \"Luv\". When r u going to fly me to Savannah? Pleeeease!!!!",
            "@AmericanAir @Nashinmypants lmao this is so funny",
            "@USAirways I can't wait for the @nytimes and @WSJ to find out how poorly @USAirways handled this situation. #shameful http://t.co/HHOxQPsUbA",
            "@united we've been waiting 45 min for a gate at SFO... Yet so many of them are free.  Your excellence in operational efficiency is showing",
            "@USAirways status shows \"delayed\" it was just \"waiting for takeoff\" so did it depart? It certainly didn\"t at 4:17pm. http://t.co/emRUbu4WzD",
            "@JetBlue thanks. Home to MSY. TSA precheck agents directing people after photo until scan beyond rude. One grabbed and pushed children.",
            "Who Okay'd this?!?! RT @JetBlue Our fleet's on fleek. http://t.co/knUVuOVhub",
            "@JetBlue have a cpap machine for sleep apnea. Is this OK to carry on if I also have a small bag for clothes?",
            "@AmericanAir booked AA3370 departing JFK 2/25/15. It was booked via BA and I want to change my FF# to AA can you do that for me via Twitter? ",
            "Includes @KCIAirport “@SouthwestAir: Inclement weather may impact scheduled service in. ReFlight Booking Problems options available: http://t.co/KeyrpFlHil” ",
            "@AmericanAir thanks 😩. idk if it still Late Flight but I hope I get it tonight 😭 ", "@JetBlue of course !!!! ",
            "@AmericanAir AA919 flight attendant freaks out and leaves aircraft as passengers react to a 24h delay and cattle treatment. Surreal! ",
            "@AmericanAir How do I check? Reservation for Joe Watson and Kelsey Jennings. We were on hold for 2 hours. Waiting for call back now. ETA? ",
            "@USAirways Well I did miss it. But gate agents had rebooked boarding pass waiting when I landed. Time for lunch &amp; a beverage. Easy cheesy ",
            "@USAirways it's been three weeks since I was specifically told I would get a call back from your folks in AZ- should I keep being patient?",
            "@AmericanAir I'm going to speak with customer service at the airport tomorrow morning and see what my options are. I need a flight tomorrow",
            "@JetBlue what are the chances of one of your flights leaving at 6am out of Newark nj being Cancelled Flightled tomorrow? ",
            "@AmericanAir American Airlines. ",
            "@JetBlue @MrJustyn I heard companies were studying popular lingo for advertising but this is just depressing and embarrassing. ",
            "@JetBlue just sat on a plane for 3 hours in Dulles #insane #ijustwanttobeinBoston #thanksDC ",
            "@USAirways I was... 4 tomorrow. I missed my meeting today, &amp; it was pointless 2 pay hotel today when the purpose of my trip has been screwed ",
            "@JetBlue What's your excuse this time for 1117 delay from LGA to TPA? I know the plane is in the air.",
            "@SouthwestAir aren't you based in Chicago? Why are you doing a hunt in LA and not your home city????!! Please bring one home",
            "@AmericanAir I really can't there though to an agent, and I am worried about my reservation. Can you help me out!",
            "@USAirways How can I change without penalty and not have to call customer service ",
            "@AmericanAir Im trying to call and book a reward ticket on one world partners but your automated system wont let me talk to any1.  Great job ",
            "@JetBlue thank you for getting me home. And despite all odds I have reunited with my delinquent Southwest luggage. Now homeward ",
            "@USAirways never in my life have I dealt with such poor customer service, irresponsible staff and lack of care LGA-IAH day 2, baggage in NC? ",
            "@united no worries Your customer service gets a bad wrap but just spoke w agent who saved me huge amounts of time &amp; apologized for yesterday ",
            "@JetBlue it was at JFK airport right now ",
            "@USAirways so I guess you are ok with people being sexually assaulted on your flights nice customer service ",
            "@AmericanAir flight home Cancelled Flightled today.  Any way we can get another flight to NYC from Texas? 4 hour wait for a call back from airline",
            "@AmericanAir what's done is done. Not much you can do at this point. Trip is already over.",
            "@AmericanAir after running from one flight, because we had 10 mins, to our next flight, we then sat on our plane for an hour. ",
            "@JetBlue thanks for the help ",
            "@AmericanAir really? Not even worthy of a response. This is beginning of a social media alert to the world that AA and @USAirways are useles ",
            "@JetBlue thank you for the refund of the change fee for a recent flight affected by our bizarre winter. Excellent customer service and focus ",
            "@SouthwestAir you are failing! Diverted, stuck and no communication! Make a decision and let us go!!!! 😞😡 flight #4229 ",
            "@SouthwestAir I'm really craving your pretzels, please send me some.",
            "@AmericanAir 24 hrs &amp; 2 cncld flights Late Flightr I've landed in PHL. Now 30 mins &amp; counting on tarmac waiting for gate. Pls do better than this.",
            "@USAirways on hold for 1 hour and 14 min trying to find the luggage flight Cancelled Flightled where is luggage? http://t.co/i1SfMI7zat ",
            "@SouthwestAir Thanks. I did go through these motions shortly after my flight yesterday. I wonder how quickly flight attendants are notified. ",
            "@JetBlue  if only the show was on the flight.  No ABC.  Oh well.  I'll live.  #nexttime #andthewinneris...",
            "@SouthwestAir baggage claim has already changed 2x...most recent had 3 bags come out and then stop...claim team has no idea what's going on",
            "@USAirways so far I've gotten six different answers",
            "@united my golf bag didn't have a top cover + staffers said they couldn't check without a type of cover or wrap. Forced to leave the bag...",
            "@united where is my bag?? I'm in Mexico about to go build a house &amp; my suitcase never got on my flight from CLE w me. I need it. SAN68059M",
            "@USAirways how long is that flight? http://t.co/bCwckWtnlE ",
            "@SouthwestAir  Mad love http://t.co/4ojrSDWPkK NYC- ",
            "@USAirways @SeanVRose Sean - keep in mind if you call...plan on being on hold for 3+ hours ",
            "@JetBlue thanks to Julian at login for getting me onto an earlier flight back to DCA ",
            "@USAirways can't get back lost time",
            "@SouthwestAir So I guess you can get to the airport too early!  Need to wait 10mins to checkin. Really? ",
            "@USAirways that is certainly not the impression she's under.", "@JetBlue thank you! ",
            "@AmericanAir not sure what this means but son and I will certainly have operational needs for seats during Flt. 1679 next Friday, yet... ",
            "@AmericanAir of course it wasn't your intention, issue lies in lack of response. she did contact you directly; she sat on hold for 50 mins",
            "@united UA1534 has now had 11 different departure times. Wtf. Make up your mind. ",
            "@SouthwestAir Had a great trip this past week to Vegas for work; and had this pic over the Southwest on Southwest! http://t.co/a3YCFlaLxV ",
            "@VirginAmerica what happened to Doom?! ",
            "@JetBlue sorry to report we are stuck on Tarmac.. Being held so #notwheelsup ",
            "@united yes. Houston Int'l, Bush.",
            "@united it's 430am and wife still doesn't have her luggage which was promised by 8pm and said to be on its way File number: DCA48810M #Fail",
            "@united again I ask, who can I call to get this fixed? Tweeting me BS questions to stall only makes things worse. Phone number please. ",
            "@united flight attendant doesn’t understand not understanding English doesn’t mean they are deaf. Stop yelling English slowly to them. ",
            "@united I forgot that Intl flights out of LAX don't go from Intl Terminal! Easiest re-check in ever! woo!",
            "@united is pri boarding for \"Active Military\" or only \"In Uniform?\" 90% can't travel in uniform for OPSEC reason, even on official travel ",
            "@USAirways 1899. Thanks ", "@united now arrives LAX @ 8:03 am ",
            "@AmericanAir I can't!!!  No one can't get to \"hold\".  You can't get past the automated reply.  It hangs up on you.  #FRUSTRATED ",
            "@JetBlue do you know when the schedule for dec 2015 will be released? ",
            "@AmericanAir got another flight. Thanks you ",
            "@united you're the reason this whole travel experience has been a nightmare",
            "@SouthwestAir flt 3260 out of mht. Have fun with my kids and grandkids 10 of them!!  Jack says hi! http://t.co/BHOOiyT6ZQ ",
            "@AmericanAir we are waiting flight 919 !\nWe are at JFK for about 24h !! #NewYork #919 #viracopos #AmericanAirlines http://t.co/3FheS0lPMU ",
            "@united it was UA flight 1001! Now I'm currently stuck in Portland because I missed my ride because of the 3 hour delay. #GetMartyHome",
            "@USAirways flight 645 to Phoenix deboards passengers going to Salt Lake City because they can't resolve a simple bathroom issue. #fail",
            "@SouthwestAir why does the customer service have rather inconsistent information ",
            "@AmericanAir Yes and without my bags. 2 first class tickets to Tahiti would be nice. Just saying ",
            "@SouthwestAir when will the winners of #DestinationDragons be announced? ",
            "@USAirways Don't tell me that. Tell me what I can actually DO to reach someone. I don't mind being put on hold but it won't even do THAT.",
            "@SouthwestAir had to rebook through Atlanta &amp; now drive to #Nashville. Had to pay ridiculous price difference. Bad weather good for business"
    );
}
